### ISSUE TITLE
some plugin have plugin formats that work only with certain architectures

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-registry#52]
'Note : MacOS Audio Unit supports Intel architecture only. Use the VST variants for ARM support.'

https://github.com/igorski/fogpad/releases/tag/1.0.3-3.7.10

yaml structure does not account for this possibility

**Comment by kmturley** [comment]
It is common for plugin authors to provide separate zip files per architecture. Otherwise you are downloading plugins you can't run.

Open Audio Stack Registry assumes one architecture per file, and I think it's a good standard to enforce.

This ticket could be opened for the plugin author to separate out architectures into different release files.
