### ISSUE TITLE
image standards

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-registry#59]
looking at the images, theyre all at different ratios, resolutions, etc.

having a standard would enable things like this
https://github.com/studiorack/studiorack-site/issues/20

we can have unstandarised images when you click into the plugin but not for its cover image like below

![17342788182538193197278625054950](https://github.com/user-attachments/assets/44c5efd0-b456-42e1-b112-acb02bd419ce)

related https://github.com/open-audio-stack/open-audio-stack-registry/issues/45

**Comment by kmturley** [comment]
Looking at other plugin websites, they have the same issue:
https://www.kvraudio.com/plugins/the-newest-plugins

The issue is that every plugin has different ratio of width vs height. Some are square, some horizontal some vertical.

With StudioRack I made the same decision to allow any ratio, as cropping parts off images doesn't make sense and looks strange.

I get around this by resizing thumbnail images on the list to the same width, which shows a sneak peak of each plugin:
https://studiorack.github.io/studiorack-site/instruments

Then on the plugin detail page, images are shown full size and centered:
- Square: https://studiorack.github.io/studiorack-site/instruments/vastdynamics/com.vastdynamics.vast2
- Horizontal: https://studiorack.github.io/studiorack-site/instruments/sjoerdvankreel/io.github.sjoerdvankreel.firefly_synth
- Vertical: https://studiorack.github.io/studiorack-site/effects/studiorack/wolf-shaper

This way there is more consistency on the list page, and the detail page shows the full plugin UI no matter the dimensions and ratio.

If we add custom thumbnails for the list page, it requires resizing and cropping another image for every plugin added.
This is something which could be done automatically but a server-side script, rather than manually.

I prefer to keep the plugin spec simpler, and lower effort to add plugins for now. Rather than adding more work.

By the way, when StudioRack list page loads, it only loads the images in view. So even if they are high resolution, they don't all get loaded at once. They are lazy-loaded as you scroll.

So in summary, I don't agree with:
- Multiple images for list/detail view
- Forcing images to be the same resolution
- Forcing images to be the same width

But I do agree there should be some standards around images. I have already updated the Registry specification to say:

> Image preview url (https). Allows users to preview the user interface of the plugin before downloading. Technically this could be any [image file format](https://caniuse.com/?search=image%20format), but we recommend .jpg as it is compressed and widely supported. Tips: Crop to plugin UI edges, avoid backgrounds, borders and/or drop-shadows. Can be any shape/dimension (square, rectangle) but limit size to around 1000px to optimize loading times for large lists of plugins.
https://docs.google.com/document/d/14ljz4XNXr02xgdDHksPMl2vaM-Jn-YnJ_VzI1WsvSKQ/edit?tab=t.0#heading=h.ug9e3ljuigte

So I think this request is already covered in the specification document.

And the Registry plugin validation recommends to use jpg if another format is used.
https://github.com/open-audio-stack/open-audio-stack-core/blob/main/src/helpers/package.ts#L60

Later it could be extended to check image minimum size.

**Comment by RustoMCSpit** [comment]
> If we add custom thumbnails for the list page, it requires resizing and cropping another image for every plugin added.
This is something which could be done automatically but a server-side script, rather than manually.

it could and should be done by the plugin uploader. this is just telling devs to give us a standardised image. this isnt labor we should have to do for them. yes, that slightly raises the bar of difficulty in uploading but i find it worth it. i understand you want to keep the barrier of entry as low as possible but it looks like a mess lol.

another strategy is to do what i did for this plugin and instead make an image out of text rather than the gui itself, it's less informative however

![image](https://github.com/user-attachments/assets/a17fcc29-d212-4d4a-a5d5-0c3141f4180d)


> I prefer to keep the plugin spec simpler, and lower effort to add plugins for now. Rather than adding more work.

is .jxl allowed?
